Hw03 frequency analysis
DmitriyPanov1/otus_home_work pull request #3
Opened 2024-06-26 07:56 UTC by DmitriyPanov1

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-06-26 09:19 UTC, agneum requested changes
Спасибо за вариант решения. 
Хорошая работа, однако не хватает новых юнит-тестов, поэтому возвращаю задачу на доработку.
Итого: 5 баллов из 10

2024-06-26 09:19 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	}
Для разделения строки на слова рекомендовал бы использовать https://pkg.go.dev/strings#Fields или https://pkg.go.dev/strings#FieldsFunc или регулярные выражения

2024-06-26 09:19 UTC, agneum commented on hw03_frequency_analysis/top_test.go
> +var taskWithAsteriskIsCompleted = true
Не хватает новых юнит-тестов

2024-06-26 09:29 UTC, DmitriyPanov1 commented on hw03_frequency_analysis/top_test.go
> +var taskWithAsteriskIsCompleted = true
1) А разве те тесты что есть не покрывают полностью функционал ? 
2) Я не понимаю каких кейсов не хватает ? 

Спасибо

2024-06-26 18:18 UTC, DmitriyPanov1 commented on hw03_frequency_analysis/top_test.go
> +var taskWithAsteriskIsCompleted = true
Покрытие теста 100%
![Uploading image.png…]()

2024-06-27 03:14 UTC, agneum commented on hw03_frequency_analysis/top_test.go
> +var taskWithAsteriskIsCompleted = true
Спасибо за вопросы
1. Верно, не покрывают. Можно написать код, который будет проходить имеющиеся тесты, но в некоторых граничных случаях будет работать некорректно.
2. Например, когда уникальных слов в строке менее 10.

В критериях оценки есть пункт, что добавлены **новые** юнит-тесты
В описании задачи указано, что `Дополнительное задание на баллы не влияет`, т.е. изменение флага `taskWithAsteriskIsCompleted` не считается новыми юнит-тестами.

2024-06-27 13:39 UTC, agneum approved these changes
Спасибо за тесты. Отличная работа
10/10

2024-06-27 14:20 UTC, merged